<?php

namespace Database\Seeders;

use App\Models\Department;
use Illuminate\Database\Seeder;

class DepartmentSeeder extends Seeder
{
    public function run(): void
    {
        $departments = [
            [
                'slug' => 'agriculture-livestock-fisheries',
                'name_en' => 'Agriculture, Livestock and Fisheries',
                'name_sw' => 'Kilimo, Mifugo na Uvuvi',
                'mandate_en' => 'To promote sustainable agriculture, livestock, and fisheries management for food security and economic development in Busia County.',
                'mandate_sw' => 'Kukuza kilimo endelevu, mifugo, na uimamizi wa uvuvi kwa ajili ya usalama wa chakula na maendeleo ya kiuchumi katika Kaunti ya Busia.',
                'vision_en' => 'To be a leading county in agricultural production and food security.',
                'vision_sw' => 'Kuwa kaunti inayoongoza katika uzalishaji wa kilimo na usalama wa chakula.',
                'mission_en' => 'To transform agriculture through innovative technologies and sustainable practices.',
                'mission_sw' => 'Kubadilisha kilimo kupitia teknolojia bunifu na mbinu endelevu.',
                'functions_en' => [
                    'Provision of agricultural extension services',
                    'Promotion of livestock development',
                    'Management of fisheries and aquaculture',
                    'Control of plant and animal diseases',
                ],
                'functions_sw' => [
                    'Utoaji wa huduma za ugani wa kilimo',
                    'Ukuaji wa maendeleo ya mifugo',
                    'Usimamizi wa uvuvi na ufugaji wa samaki',
                    'Udhibiti wa magonjwa ya mimea na wanyama',
                ],
                'achievements_en' => [
                    'Successfully distributed 50,000 bags of subsidized fertilizer in 2023',
                    'Vaccinated over 100,000 cattle against Foot and Mouth Disease',
                ],
                'achievements_sw' => [
                    'Imefanikiwa kusambaza mifuko 50,000 ya mbolea ya ruzuku mwaka wa 2023',
                    'Ilichanja zaidi ya ng\'ombe 100,000 dhidi ya ugonjwa wa miguu na mdomo',
                ],
                'email' => 'agriculture@busiacounty.go.ke',
                'icon' => 'Sprout',
                'is_external' => false,
            ],
            [
                'slug' => 'health-services-sanitation',
                'name_en' => 'Health Services and Sanitation',
                'name_sw' => 'Huduma za Afya na Usafi',
                'mandate_en' => 'To provide accessible, affordable, and high-quality healthcare and sanitation services to all residents of Busia County.',
                'mandate_sw' => 'Kutoa huduma za afya na usafi zinazofikika, na za hali ya juu kwa wakazi wote wa Kaunti ya Busia.',
                'vision_en' => 'A healthy and productive county population.',
                'vision_sw' => 'Idadi ya watu ya kaunti yenye afya na tija.',
                'mission_en' => 'To build a progressive clinical and public health system.',
                'mission_sw' => 'Kujenga mfumo wa afya wa kliniki na umma wenye maendeleo.',
                'functions_en' => [
                    'Management of county health facilities',
                    'Public health and sanitation management',
                    'Disease surveillance and control',
                    'Promotion of primary healthcare',
                ],
                'functions_sw' => [
                    'Usimamizi wa vituo vya afya vya kaunti',
                    'Usimamizi wa afya ya umma na usafi',
                    'Ufuatiliaji na udhibiti wa magonjwa',
                    'Ukuaji wa huduma ya afya ya msingi',
                ],
                'achievements_en' => [
                    'Upgraded Busia County Referral Hospital with modern ICU equipment',
                    'Achieved 95% immunization coverage across the county',
                ],
                'achievements_sw' => [
                    'Iliboresha Hospitali ya Rufaa ya Kaunti ya Busia na vifaa vya kisasa vya ICU',
                    'Ilifikia 95% ya chanjo kote kaunti',
                ],
                'email' => 'health@busiacounty.go.ke',
                'icon' => 'Stethoscope',
                'is_external' => false,
            ],
            [
                'slug' => 'education-youth-gender-sports',
                'name_en' => 'Education, Youth, Gender and Sports',
                'name_sw' => 'Elimu, Vijana, Jinsia na Michezo',
                'mandate_en' => 'To empower the youth and promote education, gender equality, and sporting excellence in Busia.',
                'mandate_sw' => 'Kuwezesha vijana na kukuza elimu, usawa wa jinsia, na ubora wa michezo huko Busia.',
                'vision_en' => 'An educated, empowered, and socially inclusive society.',
                'vision_sw' => 'Jamii iliyoelimika, iliyoidhinishwa, na inayojumuisha kijamii.',
                'mission_en' => 'To provide quality early childhood education and youth empowerment.',
                'mission_sw' => 'Kutoa elimu bora ya utotoni na uwezeshaji wa vijana.',
                'functions_en' => [
                    'Early childhood development education (ECDE)',
                    'Youth empowerment and polytechnics',
                    'Sports development and infrastructure',
                    'Gender and social services',
                ],
                'functions_sw' => [
                    'Elimu ya maendeleo ya utotoni (ECDE)',
                    'Uwezeshaji wa vijana na vyuo vya ufundi',
                    'Maendeleo ya michezo na miundombinu',
                    'Jinsia na huduma za kijamii',
                ],
                'achievements_en' => [
                    'Constructed 50 new ECDE classrooms in the last financial year',
                    'Disbursed over KSh 100M in bursaries to needy students',
                ],
                'achievements_sw' => [
                    'Ilijenga madarasa 50 mapya ya ECDE katika mwaka wa fedha uliopita',
                    'Ilitoa zaidi ya KSh 100M kama bursary kwa wanafunzi wenye uhitaji',
                ],
                'email' => 'education@busiacounty.go.ke',
                'icon' => 'GraduationCap',
                'is_external' => false,
            ],
            [
                'slug' => 'finance-economic-planning',
                'name_en' => 'Finance and Economic Planning',
                'name_sw' => 'Fedha na Mipango ya Kiuchumi',
                'mandate_en' => 'To ensure effective mobilization, allocation, and management of county financial resources.',
                'mandate_sw' => 'Kuhakikisha uhamasishaji, ugawaji, na usimamizi madhubuti wa rasilimali za kifedha za kaunti.',
                'vision_en' => 'Excellence in financial management and planning.',
                'vision_sw' => 'Ubora katika usimamizi wa fedha na mipango.',
                'mission_en' => 'To provide leadership in financial and economic policy formulation.',
                'mission_sw' => 'Kutoa uongozi katika uundaji wa sera za kifedha na kiuchumi.',
                'functions_en' => [
                    'Budget formulation and management',
                    'Revenue collection and management',
                    'Economic planning and research',
                    'Asset and liability management',
                ],
                'functions_sw' => [
                    'Uundaji wa bajeti na usimamizi',
                    'Ukusanyaji wa mapato na usimamizi',
                    'Mipango ya kiuchumi na utafiti',
                    'Usimamizi wa mali na dhima',
                ],
                'achievements_en' => [
                    'Consistently automated revenue collection reaching 80% targets',
                    'Developed the County Integrated Development Plan (CIDP) 2023-2027',
                ],
                'achievements_sw' => [
                    'Iliimarisha ukusanyaji wa mapato kufikia 80% ya malengo',
                    'Iliandaa Mpango Jumuishi wa Maendeleo ya Kaunti (CIDP) 2023-2027',
                ],
                'email' => 'finance@busiacounty.go.ke',
                'icon' => 'Wallet',
                'is_external' => false,
            ],
            [
                'slug' => 'infrastructure-energy-transport',
                'name_en' => 'Infrastructure, Energy and Transport',
                'name_sw' => 'Miundombinu, Nishati na Usafiri',
                'mandate_en' => 'To develop and manage modern infrastructure for sustainable economic growth.',
                'mandate_sw' => 'Kukuza na kusimamia miundombinu ya kisasa kwa ukuaji wa kiuchumi endelevu.',
                'vision_en' => 'Robust infrastructure for a prosperous Busia.',
                'vision_sw' => 'Miundombinu imara kwa Busia yenye ustawi.',
                'mission_en' => 'To design, construct and maintain county roads and public works.',
                'mission_sw' => 'Kubuni, kujenga na kudumisha barabara za kaunti na kazi za umma.',
                'functions_en' => [
                    'Construction and maintenance of county roads',
                    'Public works and building services',
                    'Promotion of energy development',
                    'Transport management and safety',
                ],
                'functions_sw' => [
                    'Ujenzi na matengenezo ya barabara za kaunti',
                    'Kazi za umma na huduma za ujenzi',
                    'Ukuaji wa maendeleo ya nishati',
                    'Usimamizi wa uchukuzi na usalama',
                ],
                'achievements_en' => [
                    'Tarmacked over 50km of urban roads within Busia town',
                    'Installed 200 high-mast solar lights in rural markets',
                ],
                'achievements_sw' => [
                    'Iliweka lami zaidi ya kilomita 50 ya barabara za mijini ndani ya mji wa Busia',
                    'Iliweka taa 200 za mlingoti mrefu za jua katika masoko ya vijijini',
                ],
                'email' => 'infrastructure@busiacounty.go.ke',
                'icon' => 'HardHat',
                'is_external' => false,
            ],
            [
                'slug' => 'lands-housing-urban-development',
                'name_en' => 'Lands, Housing and Urban Development',
                'name_sw' => 'Ardhi, Nyumba na Maendeleo ya Mijini',
                'mandate_en' => 'To manage land resources and promote urban planning and housing development.',
                'mandate_sw' => 'Kusimamia rasilimali za ardhi na kukuza mipango ya miji na maendeleo ya nyumba.',
                'vision_en' => 'Excellence in land management and urban aesthetics.',
                'vision_sw' => 'Ubora katika usimamizi wa ardhi na urembo wa mijini.',
                'mission_en' => 'To spatial plan and promote sustainable urban development.',
                'mission_sw' => 'Kupanga maeneo na kukuza maendeleo endelevu ya mijini.',
                'functions_en' => [
                    'Land surveying and mapping',
                    'Physical planning and urban management',
                    'Housing development and management',
                    'Land administration and valuation',
                ],
                'functions_sw' => [
                    'Upimaji wa ardhi na ramani',
                    'Upangaji wa kimwili na usimamizi wa mijini',
                    'Maendeleo ya nyumba na usimamizi',
                    'Utawala wa ardhi na tathmini',
                ],
                'achievements_en' => [
                    'Digitalized 60% of land records in the county registry',
                    'Completed the Busia and Malaba Municipality spatial plans',
                ],
                'achievements_sw' => [
                    'Iliweka katika mfumo wa kidijitali 60% ya rekodi za ardhi katika sajili ya kaunti',
                    'Ilikamilisha mipango ya anga ya Manispaa ya Busia na Malaba',
                ],
                'email' => 'lands@busiacounty.go.ke',
                'icon' => 'Map',
                'is_external' => false,
            ],
            [
                'slug' => 'water-environment-natural-resources',
                'name_en' => 'Water, Environment and Natural Resources',
                'name_sw' => 'Maji, Mazingira na Rasilimali za Asili',
                'mandate_en' => 'To protect the environment and provide clean water to all citizens.',
                'mandate_sw' => 'Kulinda mazingira na kutoa maji safi kwa raia wote.',
                'vision_en' => 'Sustainable natural resource management.',
                'vision_sw' => 'Usimamizi endelevu wa rasilimali za asili.',
                'mission_en' => 'To conserve environment and increase water access.',
                'mission_sw' => 'Kuhifadhi mazingira na kuongeza upatikanaji wa maji.',
                'functions_en' => [
                    'Water resource development and management',
                    'Environmental conservation and protection',
                    'Solid waste management',
                    'Climate change adaptation and mitigation',
                ],
                'functions_sw' => [
                    'Maendeleo ya rasilimali za maji na usimamizi',
                    'Uhifadhi wa mazingira na ulinzi',
                    'Usimamizi wa taka ngumu',
                    'Kukabiliana na mabadiliko ya hali ya hewa',
                ],
                'achievements_en' => [
                    'Increased water access coverage from 45% to 62%',
                    'Planted over 1 million trees in county water catchment areas',
                ],
                'achievements_sw' => [
                    'Iliongeza kiwango cha upatikanaji wa maji kutoka 45% hadi 62%',
                    'Ilipanda miche ya miti zaidi ya milioni 1 katika maeneo ya vyanzo vya maji',
                ],
                'email' => 'water@busiacounty.go.ke',
                'icon' => 'Droplets',
                'is_external' => false,
            ],
            [
                'slug' => 'trade-industry-investment',
                'name_en' => 'Trade, Industry and Investment',
                'name_sw' => 'Biashara, Viwanda na Uwekezaji',
                'mandate_en' => 'To foster a vibrant trade environment and attract investment into the county.',
                'mandate_sw' => 'Kukuza mazingira ya biashara yenye nguvu na kuvutia uwekezaji katika kaunti.',
                'vision_en' => 'A globally competitive trading and investment destination.',
                'vision_sw' => 'Eneo la biashara na uwekezaji lenye ushindani duniani.',
                'mission_en' => 'To promote industrial development and fair trade practices.',
                'mission_sw' => 'Kukuza maendeleo ya viwanda na mbinu za biashara ya haki.',
                'functions_en' => [
                    'Trade promotion and development',
                    'Industrial development and support',
                    'Investment attraction and coordination',
                    'Weight and measures regulation',
                ],
                'functions_sw' => [
                    'Kukuza biashara na maendeleo',
                    'Maendeleo ya viwanda na msaada',
                    'Kuvutia uwekezaji na uratibu',
                    'Udhibiti wa uzani na vipimo',
                ],
                'achievements_en' => [
                    'Successfully hosted the Busia County Investment Conference 2023',
                    'Constructed 10 modern market sheds across sub-counties',
                ],
                'achievements_sw' => [
                    'Imefanikiwa kuandaa Mkutano wa Uwekezaji wa Kaunti ya Busia 2023',
                    'Ilijenga vibanda 10 vya soko vya kisasa kote sehemu za kaunti',
                ],
                'email' => 'trade@busiacounty.go.ke',
                'icon' => 'TrendingUp',
                'is_external' => false,
            ],
            [
                'slug' => 'ict-sustainable-development-goals',
                'name_en' => 'ICT and Sustainable Development Goals',
                'name_sw' => 'ICT na Malengo ya Maendeleo Endelevu',
                'mandate_en' => 'To lead the county\'s digital transformation and monitor progress on SDGs.',
                'mandate_sw' => 'Kuongoza mabadiliko ya kidijitali ya kaunti na kufuatilia maendeleo kwenye SDGs.',
                'vision_en' => 'A digitally empowered county society.',
                'vision_sw' => 'Jamii ya kaunti iliyoidhinishwa kidijitali.',
                'mission_en' => 'To provide efficient ICT services and promote data-driven decision making.',
                'mission_sw' => 'Kutoa huduma bora za ICT na kukuza maamuzi yanayotokana na data.',
                'functions_en' => [
                    'Automation of county services',
                    'Provision of ICT infrastructure and support',
                    'Digitization of county records',
                    'SDG monitoring and reporting',
                ],
                'functions_sw' => [
                    'Uwekaji otomatiki wa huduma za kaunti',
                    'Utoaji wa miundombinu ya ICT na msaada',
                    'Ujumuishaji wa rekodi za kaunti kidijitali',
                    'Ufuatiliaji wa SDG na kuripoti',
                ],
                'achievements_en' => [
                    'Developed and rolled out the Busia County Integrated Portal',
                    'Set up 10 community digital hubs with free internet access',
                ],
                'achievements_sw' => [
                    'Iliandaa na kuzindua Wavuti Jumuishi wa Kaunti ya Busia',
                    'Iliweka vitovu 10 vya kidijitali vya jamii vyenye mtandao wa bure',
                ],
                'email' => 'ict@busiacounty.go.ke',
                'icon' => 'Cpu',
                'is_external' => false,
            ],
            [
                'slug' => 'public-service-administration',
                'name_en' => 'Public Service and Administration',
                'name_sw' => 'Huduma ya Umma na Utawala',
                'mandate_en' => 'To ensure efficient human resource management and administrative operations.',
                'mandate_sw' => 'Kuhakikisha usimamizi mzuri wa rasilimali watu na shughuli za utawala.',
                'vision_en' => 'An efficient and effective public service.',
                'vision_sw' => 'Huduma ya umma yenye ufanisi na tija.',
                'mission_en' => 'To provide leadership in human resource management.',
                'mission_sw' => 'Kutoa uongozi katika usimamizi wa rasilimali watu.',
                'functions_en' => [
                    'Human resource management and development',
                    'County administration and decentralization',
                    'Performance management and monitoring',
                    'Enforcement of county laws',
                ],
                'functions_sw' => [
                    'Usimamizi na maendeleo ya rasilimali watu',
                    'Utawala wa kaunti na ugatuzi',
                    'Usimamizi wa utendaji na ufuatiliaji',
                    'Utekelezaji wa sheria za kaunti',
                ],
                'achievements_en' => [
                    'Implemented a biometric staff attendance system',
                    'Renovated sub-county and ward administrative offices',
                ],
                'achievements_sw' => [
                    'Ilitekeleza mfumo wa usimamizi wa mahudhurio ya wafanyakazi wa kibayometriki',
                    'Ilikarabati ofisi za utawala za sehemu za kaunti na kata',
                ],
                'email' => 'administration@busiacounty.go.ke',
                'icon' => 'ShieldCheck',
                'is_external' => false,
            ],
            [
                'slug' => 'county-assembly',
                'name_en' => 'County Assembly of Busia',
                'name_sw' => 'Bunge la Kaunti la Busia',
                'mandate_en' => 'Legislation, oversight, and representation for the people of Busia.',
                'mandate_sw' => 'Kutunga sheria, kutoa usimamizi, na kutoa uwakilishi kwa watu wa Busia.',
                'vision_en' => 'A responsive and proactive legislature.',
                'vision_sw' => 'Bunge linalojibu na linalofanya kazi kwa bidii.',
                'mission_en' => 'To enact laws and provide oversight for effective governance.',
                'mission_sw' => 'Kutunga sheria na kutoa usimamizi kwa utawala bora.',
                'functions_en' => [
                    'Enacting county laws',
                    'Approving county budgets and plans',
                    'Vetting and approving county executives',
                    'Overseeing county executive functions',
                ],
                'functions_sw' => [
                    'Kutunga sheria za kaunti',
                    'Kuidhinisha bajeti na mipango ya kaunti',
                    'Kuhakiki na kuidhinisha watendaji wa kaunti',
                    'Kusimamia shughuli za watendaji wa kaunti',
                ],
                'achievements_en' => [
                    'Passed over 15 key pieces of legislation in the last session',
                    'Successfully reviewed and approved the 2023/24 budget estimates',
                ],
                'achievements_sw' => [
                    'Ilipitisha zaidi ya vipande 15 muhimu vya sheria katika kikao kilichopita',
                    'Imenafanikiwa kupitia na kuidhinisha makadirio ya bajeti ya 2023/24',
                ],
                'email' => 'clerk@busiaassembly.go.ke',
                'icon' => 'Landmark',
                'is_external' => true,
                'external_url' => 'https://busiaassembly.go.ke',
            ],
            [
                'slug' => 'office-of-the-governor',
                'name_en' => 'Office of the Governor',
                'name_sw' => 'Ofisi ya Gavana',
                'mandate_en' => 'To provide executive leadership and strategic direction to the county government.',
                'mandate_sw' => 'Kutoa uongozi wa kiutendaji na mwelekeo wa kimkakati kwa serikali ya kaunti.',
                'vision_en' => 'A prosperous and united Busia County.',
                'vision_sw' => 'Kaunti ya Busia yenye ustawi na umoja.',
                'mission_en' => 'To lead the county towards sustainable socio-economic growth.',
                'mission_sw' => 'Kuongoza kaunti kuelekea ukuaji endelevu wa kijamii na kiuchumi.',
                'functions_en' => [
                    'Strategic leadership and coordination',
                    'Intergovernmental relations management',
                    'County communications and public relations',
                    'Legal and advisory services',
                ],
                'functions_sw' => [
                    'Uongozi wa kimkakati na uratibu',
                    'Usimamizi wa uhusiano wa serikali mbalimbali',
                    'Mawasiliano ya kaunti na uhusiano wa umma',
                    'Huduma za kisheria na ushauri',
                ],
                'achievements_en' => [
                    'Successfully coordinated the first inter-county lake region summit',
                    'Launched the Busia County Digital Transformation Roadmap',
                ],
                'achievements_sw' => [
                    'Imefanikiwa kuratibu mkutano wa kwanza wa kikanda wa maziwa ya kaunti',
                    'Ilizindua Ramani ya Mabadiliko ya Kidijitali ya Kaunti ya Busia',
                ],
                'email' => 'governor@busiacounty.go.ke',
                'icon' => 'Building',
                'is_external' => false,
            ],
        ];

        foreach ($departments as $dept) {
            Department::create($dept);
        }
    }
}
